-- CreateTable
CREATE TABLE "CabRevenue" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CabId" INTEGER NOT NULL,
    CONSTRAINT "CabRevenue_CabId_fkey" FOREIGN KEY ("CabId") REFERENCES "Cabs" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
